import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes,randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { AuthApi,SESSION,CSRF,FLOW } from '../src/auth/api.js';
import { PgAuthStore } from '../src/auth/store.js';
import { hash,Vault } from '../src/auth/crypto.js';
import { SupabaseProvider,ProviderError,type AuthProvider,type Tokens,type Identity } from '../src/auth/provider.js';
class FakeProvider implements AuthProvider {
 user:Identity={id:randomUUID(),email:'student@example.test',verified:true,mfa:false};
 refreshes=0;registerCalls=0;resets=0;rejectLogin=false;failLogout=false;known=false;used=new Set<string>();expires=Date.now()/1000+3600;
 async register(){this.registerCalls++;if(this.known)throw new ProviderError(400);}
 async login(){if(this.rejectLogin)throw new ProviderError();return this.tokens();}
 tokens():Tokens{return {access_token:'access-'+this.user.id,refresh_token:'refresh-secret-'+this.user.id,expires_at:this.expires};}
 async identity(){return this.user;}
 async refresh(){this.refreshes++;this.expires=Date.now()/1000+3600;return this.tokens();}
 async forgot(){if(!this.known)throw new ProviderError(400);}
 async verify(t:string){if(t==='invalid'||this.used.has(t))throw new ProviderError();this.used.add(t);return this.tokens();}
 async updatePassword(){this.resets++;}
 async logout(){if(this.failLogout)throw new ProviderError(503);}
 async enrollMfa(){return {id:randomUUID(),secret:'test-totp-secret',uri:'otpauth://test'};}
 async verifyMfa(t:Tokens,factor:string,code:string){if(code!=='123456')throw new ProviderError();this.user.mfa=true;return this.tokens();}
 async google(redirect:string){return {url:'https://provider.example/authorize?redirect_to='+encodeURIComponent(redirect),verifier:{pkce:'private-verifier'}};}
 async exchange(code:string,v:Record<string,string>){assert.equal(code,'good-code');assert.equal(v.pkce,'private-verifier');return this.tokens();}
}
const origin='https://exam.example.test';
function cookieValue(r:Response,name:string){return r.headers.getSetCookie().find(c=>c.startsWith(name+'='))?.split(';')[0].slice(name.length+1)??'';}
export function registerAuthTests(getPool:()=>Pool,q:(sql:string,args?:unknown[])=>Promise<any[]>,native:boolean){
 function setup(){const provider=new FakeProvider();provider.user.email=provider.user.id+'@example.test';const secret=randomBytes(32).toString('base64');const app=new AuthApi(new PgAuthStore(getPool()),provider,{origin,encryptionKey:secret});const ip=randomUUID();let cookie='',csrf='';
  const call=async(path:string,body?:unknown,opts:{method?:string;origin?:string;csrf?:string;cookie?:string}={})=>{const method=opts.method??(body===undefined?'GET':'POST');const headers:Record<string,string>={origin:opts.origin??origin,cookie:opts.cookie??cookie,'x-csrf-token':opts.csrf??csrf};if(body!==undefined)headers['content-type']='application/json';return app.handle(new Request(origin+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),ip);};
  const login=async()=>{const r=await call('/auth/login',{email:provider.user.email,password:'long-password-123'});assert.equal(r.status,200);const sid=cookieValue(r,SESSION);csrf=cookieValue(r,CSRF);cookie=`${SESSION}=${sid}; ${CSRF}=${csrf}`;return {r,sid,csrf,cookie};};
  return {provider,app,call,login,secret,getCookie:()=>cookie};
 }
 test('auth: registration validates password and ignores no privilege fields',async()=>{const a=setup();assert.equal((await a.call('/auth/register',{email:'a@example.test',password:'short'})).status,400);assert.equal((await a.call('/auth/register',{email:'a@example.test',password:'long-password-123',role:'account_admin'})).status,400);assert.equal(a.provider.registerCalls,0);assert.equal((await a.call('/auth/register',{email:'a@example.test',password:'long-password-123'})).status,202);});
 test('auth: duplicate registration and forgot password use non-enumerating responses',async()=>{const a=setup();const b={email:'a@example.test',password:'long-password-123'};const one=await (await a.call('/auth/register',b)).json();a.provider.known=true;assert.deepEqual(await (await a.call('/auth/register',b)).json(),one);a.provider.known=false;const f=await (await a.call('/auth/forgot-password',{email:b.email})).json();a.provider.known=true;assert.deepEqual(await (await a.call('/auth/forgot-password',{email:b.email})).json(),f);});
 test('auth: verified login sets hardened opaque cookies; tokens encrypted at rest',async()=>{const a=setup(),{r,sid}=await a.login();for(const c of r.headers.getSetCookie()){assert.match(c,/Secure/);assert.match(c,/SameSite=Lax/);assert.match(c,/Path=\//);}assert.match(r.headers.getSetCookie().find(c=>c.startsWith(SESSION))!,/HttpOnly/);assert.equal(sid.length,43);const row=(await q('SELECT * FROM exam.auth_sessions WHERE token_hash=$1',[hash(sid)]))[0];assert.ok(row);assert.ok(!row.encrypted_tokens.includes('refresh-secret'));assert.equal(row.token_hash,hash(sid));assert.ok(!JSON.stringify(await r.json()).includes('access_token'));assert.equal((await a.call('/account/profile')).status,200);});
 test('auth: wrong password and unverified email cannot create sessions',async()=>{const a=setup();a.provider.rejectLogin=true;assert.equal((await a.call('/auth/login',{email:'a@example.test',password:'wrong'})).status,401);a.provider.rejectLogin=false;a.provider.user.verified=false;assert.equal((await a.call('/auth/login',{email:'a@example.test',password:'long-password-123'})).status,403);assert.equal((await q('SELECT count(*)::int n FROM exam.auth_sessions WHERE user_id=$1',[a.provider.user.id]))[0].n,0);});
 test('auth: origin and CSRF defenses block cross-site login and profile changes',async()=>{const a=setup();assert.equal((await a.call('/auth/login',{email:'a@example.test',password:'long-password-123'},{origin:'https://evil.example'})).status,403);await a.login();const profile={display_name:'Naresh',preferred_language:'en',timezone:'Asia/Kolkata'};assert.equal((await a.call('/account/profile',profile,{method:'PATCH',csrf:'bad'})).status,403);assert.equal((await a.call('/account/profile',profile,{method:'PATCH'})).status,200);assert.equal((await a.call('/account/profile',{...profile,roles:['account_admin']},{method:'PATCH'})).status,400);});
 test('auth: profile belongs to session identity and rejects injected user IDs',async()=>{const a=setup();await a.login();const r=await a.call('/account/profile');assert.equal((await r.json()).id,a.provider.user.id);assert.equal((await a.call('/account/profile',{display_name:'Other',preferred_language:'en',timezone:'Asia/Kolkata',user_id:randomUUID()},{method:'PATCH'})).status,400);});
 test('auth: logout revokes session even if provider signout is unavailable',async()=>{const a=setup(),{cookie,csrf}=await a.login();a.provider.failLogout=true;assert.equal((await a.call('/auth/logout',{})).status,200);assert.equal((await a.call('/account/profile',undefined,{cookie,csrf})).status,401);});
 test('auth: session fixation prevented and old cookie revoked after login',async()=>{const a=setup(),one=await a.login(),two=await a.login();assert.notEqual(one.sid,two.sid);assert.equal((await a.call('/account/profile',undefined,{cookie:one.cookie})).status,401);assert.equal((await a.call('/account/profile')).status,200);});
 test('auth: idle expiry and suspension deny access',async()=>{const a=setup(),{sid}=await a.login();await q("UPDATE exam.auth_sessions SET idle_expires_at=now()-interval '1 second' WHERE token_hash=$1",[hash(sid)]);assert.equal((await a.call('/account/profile')).status,401);await a.login();await q("UPDATE exam.users SET status='suspended' WHERE id=$1",[a.provider.user.id]);assert.equal((await a.call('/account/profile')).status,401);});
 test('auth: login rate limiting persists in PostgreSQL',async()=>{const a=setup();a.provider.rejectLogin=true;let status=0;for(let i=0;i<11;i++)status=(await a.call('/auth/login',{email:randomUUID()+'@example.test',password:'wrong'})).status;for(let i=0;i<22;i++)status=(await a.call('/auth/login',{email:randomUUID()+'@example.test',password:'wrong'})).status;assert.equal(status,429);});
 test('auth: password reset requires recovery session and revokes all account sessions',async()=>{const a=setup(),old=await a.login();assert.equal((await a.call('/auth/reset-password',{password:'new-long-password'})).status,403);const verification=await a.call('/auth/verify',{token_hash:'valid-recovery',type:'recovery'});assert.equal(verification.status,200);const recoveryCookie=SESSION+'='+cookieValue(verification,SESSION),recoveryCsrf=cookieValue(verification,CSRF);assert.equal((await a.call('/account/profile',undefined,{cookie:recoveryCookie})).status,403);assert.equal((await a.call('/auth/reset-password',{password:'new-long-password'},{cookie:recoveryCookie,csrf:recoveryCsrf})).status,200);assert.equal(a.provider.resets,1);assert.equal((await a.call('/account/profile',undefined,{cookie:old.cookie})).status,401);assert.equal((await a.call('/auth/reset-password',{password:'other-long-password'},{cookie:recoveryCookie,csrf:recoveryCsrf})).status,401);});
 test('auth: invalid/replayed email verification fails; signup verification logs in',async()=>{const a=setup();assert.equal((await a.call('/auth/verify',{token_hash:'invalid',type:'signup'})).status,401);assert.equal((await a.call('/auth/verify',{token_hash:'once',type:'signup'})).status,200);assert.equal((await a.call('/auth/verify',{token_hash:'once',type:'signup'})).status,401);});
 test('auth: Google PKCE callback binds browser, expires once, rejects replay',async()=>{const a=setup(),r=await a.call('/auth/google',{});assert.equal(r.status,200);const state=cookieValue(r,FLOW),cookie=FLOW+'='+state;assert.equal((await a.call('/auth/google/callback?state='+state+'&code=good-code',undefined,{cookie:''})).status,400);const valid=await a.call('/auth/google/callback?state='+state+'&code=good-code',undefined,{cookie});assert.equal(valid.status,303);assert.equal(valid.headers.get('location'),'/auth');assert.ok(cookieValue(valid,SESSION));assert.equal((await a.call('/auth/google/callback?state='+state+'&code=good-code',undefined,{cookie})).status,400);});
 test('auth: expired OAuth flow does not grant access',async()=>{const a=setup(),r=await a.call('/auth/google',{}),state=cookieValue(r,FLOW);await q("UPDATE exam.auth_flows SET expires_at=now()-interval '1 second' WHERE token_hash=$1",[hash(state)]);assert.equal((await a.call('/auth/google/callback?state='+state+'&code=good-code',undefined,{cookie:FLOW+'='+state})).status,400);});
 test('auth: MFA challenges require CSRF and rotate the session on success',async()=>{const a=setup(),old=await a.login();assert.equal((await a.call('/auth/mfa/enroll',{}, {csrf:'wrong'})).status,403);const enrollment=await (await a.call('/auth/mfa/enroll',{})).json();assert.ok(enrollment.id);assert.equal((await a.call('/auth/mfa/verify',{factor_id:enrollment.id,code:'000000'})).status,401);const r=await a.call('/auth/mfa/verify',{factor_id:enrollment.id,code:'123456'});assert.equal(r.status,200);assert.notEqual(cookieValue(r,SESSION),old.sid);assert.equal((await a.call('/account/profile',undefined,{cookie:old.cookie})).status,401);});
 test('auth: student cannot escalate role; admin requires MFA and audit',async()=>{const a=setup();await a.login();const target=randomUUID();await q('SELECT exam.provision_user($1)',[target]);const body={user_id:target,role:'support_admin',grant:true,reason:'Approved support operator'};assert.equal((await a.call('/account/roles',body)).status,403);await q("INSERT INTO exam.user_roles(user_id,role_id) SELECT $1,id FROM exam.roles WHERE code='account_admin'",[a.provider.user.id]);assert.equal((await a.call('/account/roles',body)).status,403);a.provider.user.mfa=true;assert.equal((await a.call('/account/roles',body)).status,200);assert.equal((await q("SELECT count(*)::int n FROM exam.admin_audit_logs WHERE entity_id=$1 AND action='account.role_change'",[target]))[0].n,1);assert.equal((await a.call('/account/roles',{...body,user_id:a.provider.user.id})).status,400);});
 test('auth: authentication does not reset a consumed free allowance',async()=>{const a=setup();await a.login();await q('UPDATE exam.user_free_allowances SET used_count=2 WHERE user_id=$1',[a.provider.user.id]);await a.call('/auth/logout',{});await a.login();assert.equal((await q('SELECT used_count FROM exam.user_free_allowances WHERE user_id=$1',[a.provider.user.id]))[0].used_count,2);});
 test('auth: Supabase SDK generates PKCE Google URL with server-only verifier storage',async()=>{const provider=new SupabaseProvider('https://independent-test.supabase.co','test-publishable-key');const r=await provider.google(origin+'/auth/google/callback?state=test-state');const url=new URL(r.url);assert.equal(url.origin,'https://independent-test.supabase.co');assert.equal(url.searchParams.get('provider'),'google');assert.equal(url.searchParams.get('code_challenge_method'),'s256');assert.ok(url.searchParams.get('code_challenge'));assert.ok(Object.keys(r.verifier).some(k=>k.includes('code-verifier')));assert.ok(!r.url.includes('private-verifier'));});
 test('auth: cryptographic tampering rejected',()=>{const vault=new Vault(randomBytes(32).toString('base64')),sealed=vault.seal({secret:'private'});assert.deepEqual(vault.open(sealed),{secret:'private'});const parts=sealed.split('.');parts[2]='A'+parts[2].slice(1);if(parts.join('.')===sealed)parts[2]='B'+parts[2].slice(1);assert.throws(()=>vault.open(parts.join('.')));assert.throws(()=>new Vault('short'));});
 test('auth: account and confirmation pages use nonce CSP without reflecting URL secrets',async()=>{const a=setup();for(const path of ['/auth','/auth/confirm?token_hash=secret-value&type=recovery']){const r=await a.call(path);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy')!,/script-src 'nonce-/);assert.equal(r.headers.get('referrer-policy'),'no-referrer');const html=await r.text();assert.ok(!html.includes('secret-value'));assert.ok(!html.includes('localStorage'));const script=html.match(/<script nonce="[^"]+">([\s\S]*?)<\/script>/)![1];assert.doesNotThrow(()=>new Function(script));}});
 test('auth: malformed requests do not expose internal errors',async()=>{const a=setup();const r=await a.app.handle(new Request(origin+'/auth/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:'{' }),randomUUID());assert.equal(r.status,400);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await a.call('/payments')).status,404);});
 test('auth: concurrent refresh uses one provider token rotation',{skip:!native},async()=>{const a=setup();a.provider.expires=Date.now()/1000+1;await a.login();const results=await Promise.all(Array.from({length:12},()=>a.call('/account/profile')));assert.ok(results.every(r=>r.status===200));assert.equal(a.provider.refreshes,1);});
}
