import { test,before,after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,createHmac } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { Pool } from 'pg';
import { verifySignature } from '../src/payment-verification.js';
let lite:PGlite|undefined; let pool:Pool|undefined;
async function q(sql:string,args:unknown[]=[]):Promise<any[]> { return pool ? (await pool.query(sql,args)).rows : (await lite!.query(sql,args)).rows; }
async function role(name:string,sql:string,args:unknown[]=[]):Promise<any[]> {
  assert.match(name,/^exam_(runtime|identity|support|billing)$/);
  if(pool){const c=await pool.connect(); try{await c.query(`SET ROLE ${name}`);return (await c.query(sql,args)).rows;}finally{await c.query('RESET ROLE');c.release();}}
  await lite!.query(`SET ROLE ${name}`);try{return (await lite!.query(sql,args)).rows;}finally{await lite!.query('RESET ROLE');}
}
const testId=randomUUID(),examId=randomUUID(),stage=randomUUID(),syllabus=randomUUID(),question=randomUUID(),version=randomUUID(),section=randomUUID(),mock=randomUUID();
const key=()=>randomUUID();
async function user(){const id=key();await role('exam_identity','SELECT exam.provision_user($1)',[id]);return id;}
async function start(u:string,k=key(),t=testId){return (await role('exam_runtime','SELECT exam.start_attempt($1,$2,$3) AS id',[u,t,k]))[0].id as string;}
async function used(u:string){return (await q('SELECT used_count FROM exam.user_free_allowances WHERE user_id=$1',[u]))[0].used_count;}
async function admin(){const u=await user();await q("INSERT INTO exam.user_roles(user_id,role_id) SELECT $1,id FROM exam.roles WHERE code='support_admin'",[u]);return u;}
async function order(u:string,all=true){const plan=key(),pv=key(),o=key();await q("INSERT INTO exam.subscription_plans(id,code,name,status) VALUES($1,$2,'30 days','active')",[plan,key()]);await q("INSERT INTO exam.subscription_plan_versions(id,plan_id,version,price_minor,currency,all_exams) VALUES($1,$2,1,9900,'INR',$3)",[pv,plan,all]);await q("INSERT INTO exam.payment_orders(id,user_id,plan_version_id,provider_order_id,amount_minor,currency,idempotency_key) VALUES($1,$2,$3,$4,9900,'INR',$5)",[o,u,pv,'order_'+key(),key()]);return {o,pv};}
async function pay(o:string,p='pay_'+key()){return (await role('exam_billing',"SELECT exam.activate_verified_payment($1,$2,9900,'INR',$3) AS id",[o,p,'a'.repeat(64)]))[0].id as string;}
before(async()=>{
 if(process.env.TEST_DATABASE_URL){assert.equal(process.env.ALLOW_EMPTY_TEST_DATABASE,'yes','Explicit disposable database acknowledgement required');pool=new Pool({connectionString:process.env.TEST_DATABASE_URL,max:16});assert.equal((await q("SELECT count(*)::int AS n FROM pg_namespace WHERE nspname='exam'"))[0].n,0,'Use a new empty test DB');}
 else lite=new PGlite();
 for(const name of (await readdir(new URL('../db/migrations/',import.meta.url))).filter(x=>x.endsWith('.sql')).sort()){const sql=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8');if(pool)await pool.query(sql);else await lite!.exec(sql);}
 await q("INSERT INTO exam.exams(id,family_id,slug,name) SELECT $1,id,'test-exam','Test Exam' FROM exam.exam_families WHERE code='ssc'",[examId]);
 await q("INSERT INTO exam.exam_stages(id,exam_id,code,name) VALUES($1,$2,'tier1','Tier 1')",[stage,examId]);
 await q('INSERT INTO exam.syllabus_versions(id,exam_stage_id,version) VALUES($1,$2,1)',[syllabus,stage]);
 await q("INSERT INTO exam.questions(id,origin_type) VALUES($1,'original')",[question]);
 await q("INSERT INTO exam.question_versions(id,question_id,version,difficulty,content_hash) VALUES($1,$2,1,'easy','fixture')",[version,question]);
 await q("INSERT INTO exam.question_translations VALUES($1,'en','2 + 2?','2 + 2 = 4','approved')",[version]);
 await q("INSERT INTO exam.question_options(question_version_id,option_key,display_order) VALUES($1,'A',1),($1,'B',2)",[version]);
 await q("INSERT INTO exam.question_option_translations SELECT id,'en',CASE option_key WHEN 'A' THEN '4' ELSE '5' END FROM exam.question_options WHERE question_version_id=$1",[version]);
 await q(`INSERT INTO exam.question_answer_keys VALUES($1,'{"option_key":"A"}','single_choice','fixture')`,[version]);
 await q("UPDATE exam.question_versions SET review_status='published' WHERE id=$1",[version]);
 await q("INSERT INTO exam.mock_tests(id,exam_stage_id,title,test_mode,status) VALUES($1,$2,'Fixture','full_length','published')",[mock,stage]);
 await q('INSERT INTO exam.test_versions(id,mock_test_id,version,syllabus_version_id,duration_seconds) VALUES($1,$2,1,$3,3600)',[testId,mock,syllabus]);
 await q(`INSERT INTO exam.test_sections(id,test_version_id,name,position,question_count,scoring_rule) VALUES($1,$2,'Math',1,1,'{"correct":1,"wrong_numerator":-1,"wrong_denominator":3}')`,[section,testId]);
 await q('INSERT INTO exam.test_questions(test_section_id,question_version_id,position) VALUES($1,$2,1)',[section,version]);
 await q('UPDATE exam.test_versions SET published_at=now() WHERE id=$1',[testId]);
});
after(async()=>{await pool?.end();await lite?.close();});
test('all proposed entities exist and RLS is enabled',async()=>{const rows=await q("SELECT count(*)::int AS n,bool_and(rowsecurity) AS secured FROM pg_tables WHERE schemaname='exam'");assert.ok(rows[0].n>=60);assert.equal(rows[0].secured,true);});
test('first two starts free, third requires subscription immediately',async()=>{const u=await user();const a=await start(u);assert.equal(await used(u),1);const b=await start(u);assert.equal(await used(u),2);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);const rows=await q('SELECT authorization_type FROM exam.attempt_authorizations WHERE attempt_id IN($1,$2)',[a,b]);assert.deepEqual(rows.map(x=>x.authorization_type),['free','free']);});
test('same start key replays same attempt without spending twice',async()=>{const u=await user(),k=key();const a=await start(u,k);assert.equal(await start(u,k),a);assert.equal(await used(u),1);});
test('same key with changed test rejected',async()=>{const u=await user(),k=key();await start(u,k);await assert.rejects(start(u,k,key()),/IDEMPOTENCY_CONFLICT/);});
test('refresh and provisioning on login do not reset allowance',async()=>{const u=await user(),a=await start(u);await start(u);for(let i=0;i<3;i++){await role('exam_identity','SELECT exam.provision_user($1)',[u]);await role('exam_runtime','SELECT exam.get_attempt($1,$2)',[u,a]);}assert.equal(await used(u),2);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);});
test('abandoned in-progress attempts remain consumed',async()=>{const u=await user();await start(u);await start(u);assert.equal((await q("SELECT count(*)::int n FROM exam.user_attempts WHERE user_id=$1 AND status='in_progress'",[u]))[0].n,2);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);});
test('invalid start rolls back without consuming or creating attempt',async()=>{const u=await user();await assert.rejects(start(u,key(),key()),/TEST_NOT_PUBLISHED/);assert.equal(await used(u),0);assert.equal((await q('SELECT count(*)::int n FROM exam.user_attempts WHERE user_id=$1',[u]))[0].n,0);});
test('cross-user resume and unknown identities rejected',async()=>{const u=await user(),v=await user(),a=await start(u);await assert.rejects(role('exam_runtime','SELECT exam.get_attempt($1,$2)',[v,a]),/ATTEMPT_NOT_FOUND/);await assert.rejects(start(key()),/ACCOUNT_NOT_ACTIVE/);});
test('suspended users cannot start or resume',async()=>{const u=await user(),a=await start(u);await q("UPDATE exam.users SET status='suspended' WHERE id=$1",[u]);await assert.rejects(start(u),/ACCOUNT_NOT_ACTIVE/);await assert.rejects(role('exam_runtime','SELECT exam.get_attempt($1,$2)',[u,a]),/ACCOUNT_NOT_ACTIVE/);});
test('ordinary runtime cannot mutate allowances, read keys, restore or activate payments',async()=>{await assert.rejects(role('exam_runtime','UPDATE exam.user_free_allowances SET used_count=0'),/permission denied/);await assert.rejects(role('exam_runtime','SELECT * FROM exam.question_answer_keys'),/permission denied/);await assert.rejects(role('exam_runtime','SELECT exam.restore_attempt($1,$2,$3,$4,$5)',[key(),key(),'failure','INC-1',key()]),/permission denied/);await assert.rejects(role('exam_runtime',"SELECT exam.activate_verified_payment($1,'p',1,'INR',$2)",[key(),'a'.repeat(64)]),/permission denied/);});
test('support role still requires verified administrator permission',async()=>{const u=await user(),a=await start(u);await assert.rejects(role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5)',[u,a,'server failure','INC-1',key()]),/RESTORE_FORBIDDEN/);});
test('restoration is audited, idempotent, and permits one replacement',async()=>{const u=await user(),actor=await admin(),a=await start(u);await start(u);const args=[actor,a,'confirmed server outage','INC-2026-1',key()];const x=await role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5) AS id',args);const y=await role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5) AS id',args);assert.equal(x[0].id,y[0].id);assert.equal(await used(u),1);assert.equal((await q('SELECT status FROM exam.user_attempts WHERE id=$1',[a]))[0].status,'voided');assert.equal((await q('SELECT count(*)::int n FROM exam.admin_audit_logs WHERE entity_id=$1',[a]))[0].n,1);await start(u);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);});
test('missing incident evidence rejected',async()=>{const u=await user(),a=await start(u),actor=await admin();await assert.rejects(role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5)',[actor,a,'technical failure','',key()]),/INCIDENT_AND_REASON_REQUIRED/);assert.equal(await used(u),1);});
test('audit and free usage ledger are append-only',async()=>{await assert.rejects(q("UPDATE exam.free_attempt_events SET reason='changed'"),/APPEND_ONLY/);await assert.rejects(q('DELETE FROM exam.admin_audit_logs'),/APPEND_ONLY/);});
test('verified payment grants exactly 720 hours and attempt 3',async()=>{const u=await user();await start(u);await start(u);const {o}=await order(u);const period=await pay(o);const a=await start(u);assert.equal((await q('SELECT authorization_type FROM exam.attempt_authorizations WHERE attempt_id=$1',[a]))[0].authorization_type,'subscription');assert.equal((await q('SELECT extract(epoch FROM ends_at-starts_at)::int seconds FROM exam.subscription_periods WHERE id=$1',[period]))[0].seconds,2592000);assert.equal(await used(u),2);});
test('early subscription does not change first-two-FREE rule',async()=>{const u=await user();await pay((await order(u)).o);await start(u);await start(u);assert.equal(await used(u),2);});
test('duplicate payment does not extend access again',async()=>{const u=await user(),{o}=await order(u),p='pay_'+key();assert.equal(await pay(o,p),await pay(o,p));assert.equal((await q('SELECT count(*)::int n FROM exam.payments WHERE order_id=$1',[o]))[0].n,1);});
test('wrong amount cannot create subscription',async()=>{const u=await user(),{o}=await order(u);await assert.rejects(role('exam_billing',"SELECT exam.activate_verified_payment($1,$2,1,'INR',$3)",[o,'pay_'+key(),'a'.repeat(64)]),/PAYMENT_MISMATCH/);assert.equal((await q('SELECT count(*)::int n FROM exam.user_subscriptions WHERE user_id=$1',[u]))[0].n,0);});
test('subscription expiration blocks new starts but retains existing attempt',async()=>{const u=await user();await start(u);await start(u);const period=await pay((await order(u)).o),a=await start(u);await q("UPDATE exam.subscription_periods SET starts_at=now()-interval '721 hours',ends_at=now()-interval '1 hour' WHERE id=$1",[period]);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);await role('exam_runtime','SELECT exam.get_attempt($1,$2)',[u,a]);});
test('future or revoked subscription cannot unlock mocks',async()=>{const u=await user();await start(u);await start(u);const period=await pay((await order(u)).o);await q("UPDATE exam.subscription_periods SET starts_at=now()+interval '1 hour',ends_at=now()+interval '721 hours' WHERE id=$1",[period]);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);await q("UPDATE exam.subscription_periods SET starts_at=now()-interval '1 hour',ends_at=now()+interval '719 hours',status='revoked' WHERE id=$1",[period]);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);});
test('exam-restricted subscription does not cover unrelated exam',async()=>{const u=await user();await start(u);await start(u);await pay((await order(u,false)).o);await assert.rejects(start(u),/SUBSCRIPTION_REQUIRED/);});
test('non-30-day subscription intervals rejected',async()=>{const u=await user(),{o,pv}=await order(u);await assert.rejects(q('UPDATE exam.subscription_plan_versions SET duration_days=31 WHERE id=$1',[pv]),/APPEND_ONLY/);await assert.rejects(q("INSERT INTO exam.subscription_plan_versions(plan_id,version,price_minor,currency,duration_days) SELECT plan_id,2,9900,'INR',31 FROM exam.subscription_plan_versions WHERE id=$1",[pv]),/check constraint/);const period=await pay(o);await assert.rejects(q("UPDATE exam.subscription_periods SET ends_at=starts_at+interval '31 days' WHERE id=$1",[period]),/check constraint/);});
test('paid attempt cannot manufacture free credits through restoration',async()=>{const u=await user(),actor=await admin();await start(u);await start(u);await pay((await order(u)).o);const a=await start(u);await assert.rejects(role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5)',[actor,a,'server outage','INC-9',key()]),/NOT_A_FREE_ATTEMPT/);assert.equal(await used(u),2);});
test('published question, key and test are immutable',async()=>{await assert.rejects(q("UPDATE exam.question_versions SET difficulty='hard' WHERE id=$1",[version]),/IMMUTABLE/);await assert.rejects(q("UPDATE exam.question_answer_keys SET answer_specification='{}' WHERE question_version_id=$1",[version]),/IMMUTABLE/);await assert.rejects(q('UPDATE exam.test_versions SET duration_seconds=1 WHERE id=$1',[testId]),/IMMUTABLE/);await assert.rejects(q('DELETE FROM exam.test_questions WHERE test_section_id=$1',[section]),/IMMUTABLE/);});
test('signature validation rejects altered and malformed values',()=>{const secret='test-secret',body='order|payment',sig=createHmac('sha256',secret).update(body).digest('hex');assert.equal(verifySignature(body,sig,secret),true);assert.equal(verifySignature(body+'x',sig,secret),false);assert.equal(verifySignature(body,'zz',secret),false);assert.equal(verifySignature(body,sig,''),false);});
test('native PostgreSQL: 12 simultaneous starts permit exactly 2',{skip:!process.env.TEST_DATABASE_URL},async()=>{const u=await user();const results=await Promise.allSettled(Array.from({length:12},()=>start(u)));assert.equal(results.filter(x=>x.status==='fulfilled').length,2);for(const r of results)if(r.status==='rejected')assert.match(String(r.reason),/SUBSCRIPTION_REQUIRED/);assert.equal(await used(u),2);});
test('native PostgreSQL: simultaneous retries consume once',{skip:!process.env.TEST_DATABASE_URL},async()=>{const u=await user(),k=key();const ids=await Promise.all(Array.from({length:12},()=>start(u,k)));assert.equal(new Set(ids).size,1);assert.equal(await used(u),1);});
test('native PostgreSQL: start versus restore preserves ledger',{skip:!process.env.TEST_DATABASE_URL},async()=>{const u=await user(),actor=await admin(),a=await start(u);await start(u);const results=await Promise.allSettled([start(u),role('exam_support','SELECT exam.restore_attempt($1,$2,$3,$4,$5)',[actor,a,'platform outage','INC-RACE',key()])]);assert.equal(results[1].status,'fulfilled');if(results[0].status==='rejected')assert.match(String(results[0].reason),/SUBSCRIPTION_REQUIRED/);assert.equal((await q('SELECT count(*)::int n FROM exam.admin_audit_logs WHERE entity_id=$1',[a]))[0].n,1);const total=(await q('SELECT sum(delta_used)::int n FROM exam.free_attempt_events WHERE user_id=$1',[u]))[0].n;assert.equal(await used(u),total);assert.ok(total>=0&&total<=2);});

test('native PostgreSQL: simultaneous payment activation grants one period',{skip:!process.env.TEST_DATABASE_URL},async()=>{const u=await user(),{o}=await order(u),p='pay_'+key();const ids=await Promise.all(Array.from({length:12},()=>pay(o,p)));assert.equal(new Set(ids).size,1);assert.equal((await q('SELECT count(*)::int n FROM exam.payments WHERE order_id=$1',[o]))[0].n,1);});
test('native PostgreSQL: concurrent subscribed starts and expiry enforce access',{skip:!process.env.TEST_DATABASE_URL},async()=>{const u=await user();await start(u);await start(u);const period=await pay((await order(u)).o);const ids=await Promise.all(Array.from({length:12},()=>start(u)));assert.equal(new Set(ids).size,12);assert.equal(await used(u),2);assert.equal((await q("SELECT count(*)::int n FROM exam.attempt_authorizations aa JOIN exam.user_attempts a ON a.id=aa.attempt_id WHERE a.user_id=$1 AND aa.authorization_type='subscription'",[u]))[0].n,12);await q("UPDATE exam.subscription_periods SET starts_at=now()-interval '721 hours',ends_at=now()-interval '1 hour' WHERE id=$1",[period]);const results=await Promise.allSettled(Array.from({length:12},()=>start(u)));for(const r of results){assert.equal(r.status,'rejected');if(r.status==='rejected')assert.match(String(r.reason),/SUBSCRIPTION_REQUIRED/);}assert.equal(await used(u),2);});
