import { randomBytes } from 'node:crypto';
/** Authentication-only pages. All untrusted strings are assigned with textContent. */
export function authPage(confirm=false):Response {
 const nonce=randomBytes(18).toString('base64');
 const forms=confirm?`
 <h1>Confirm your email</h1><p>Continue to verify your email or begin your password reset.</p>
 <button id="confirm">Continue securely</button>
 <form id="reset" hidden><h2>Choose a new password</h2><label>New password <input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><button>Update password</button></form>
 <p><a href="/auth">Return to sign in</a></p>`:`
 <h1>Government Exam Platform</h1><p>Account access</p>
 <form id="login"><h2>Sign in</h2><label>Email <input name="email" type="email" autocomplete="username" required></label><label>Password <input name="password" type="password" autocomplete="current-password" required></label><button>Sign in</button></form>
 <button id="google">Continue with Google</button>
 <details><summary>Create an account</summary><form id="register"><label>Email <input name="email" type="email" autocomplete="email" required></label><label>Password (at least 12 characters) <input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><button>Create account</button></form></details>
 <details><summary>Forgot password?</summary><form id="forgot"><label>Email <input name="email" type="email" autocomplete="email" required></label><button>Send reset instructions</button></form></details>
 <section id="account" hidden><h2>Your profile</h2><form id="profile"><label>Display name <input name="display_name" maxlength="100" required></label><label>Language <select name="preferred_language"><option value="en">English</option><option value="hi">Hindi</option><option value="te">Telugu</option><option value="ta">Tamil</option><option value="kn">Kannada</option><option value="ml">Malayalam</option><option value="mr">Marathi</option><option value="bn">Bengali</option><option value="gu">Gujarati</option><option value="pa">Punjabi</option><option value="or">Odia</option><option value="ur">Urdu</option></select></label><label>Timezone <input name="timezone" value="Asia/Kolkata" required></label><button>Save profile</button></form><p id="roles"></p><button id="logout">Sign out</button><button id="logout-all">Sign out of all devices</button></section>`;
 const script=`
 const message=document.getElementById('message');
 const show=(text)=>{message.textContent=text;};
 const csrf=()=>document.cookie.split('; ').find(x=>x.startsWith('__Host-exam_csrf='))?.slice('__Host-exam_csrf='.length)||'';
 async function api(path,body,method='POST'){const r=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Request failed');return result;}
 function bind(id,path,method='POST',done){const f=document.getElementById(id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const btn=f.querySelector('button');btn.disabled=true;try{const result=await api(path,Object.fromEntries(new FormData(f)),method);show(result.message||'Saved.');if(done)await done(result);}catch(e){show(e.message);}finally{btn.disabled=false;}});}
 async function profile(){try{const p=await api('/account/profile',undefined,'GET');document.getElementById('account').hidden=false;for(const k of ['display_name','preferred_language','timezone'])document.querySelector('#profile [name="'+k+'"]').value=p[k]||'';document.getElementById('roles').textContent='Roles: '+p.roles.join(', ');document.getElementById('login').hidden=true;}catch{}}
 bind('login','/auth/login','POST',profile);bind('register','/auth/register');bind('forgot','/auth/forgot-password');bind('profile','/account/profile','PATCH');bind('reset','/auth/reset-password','POST',()=>{document.getElementById('reset').hidden=true;});
 const google=document.getElementById('google');if(google)google.onclick=async()=>{try{google.disabled=true;const data=await api('/auth/google',{});location.assign(data.url);}catch(e){show(e.message);google.disabled=false;}};
 for(const id of ['logout','logout-all']){const b=document.getElementById(id);if(b)b.onclick=async()=>{try{await api('/auth/logout',{all:id==='logout-all'});location.assign('/auth');}catch(e){show(e.message);}};}
 const confirm=document.getElementById('confirm');if(confirm){const params=new URLSearchParams(location.search);const token_hash=params.get('token_hash'),type=params.get('type');history.replaceState(null,'','/auth/confirm');confirm.onclick=async()=>{confirm.disabled=true;try{const data=await api('/auth/verify',{token_hash,type});show(data.scope==='recovery'?'Email verified. Set your new password.':'Email confirmed. You can return to your account.');if(data.scope==='recovery')document.getElementById('reset').hidden=false;}catch(e){show(e.message);confirm.disabled=false;}};}else{profile();}
 `;
 return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Account access</title><style nonce="${nonce}">body{font:16px system-ui;max-width:480px;margin:40px auto;padding:20px;color:#172033;background:#f7f9fc}h1{font-size:26px}h2{font-size:20px}form,section,details{margin:20px 0}label{display:block;margin:12px 0}input,select{display:block;box-sizing:border-box;width:100%;padding:10px;margin-top:5px}button{padding:10px 15px;margin:6px 4px 6px 0;cursor:pointer}#message{white-space:pre-wrap}summary{cursor:pointer}</style></head><body><main>${forms}<p id="message" role="status" aria-live="polite"></p></main><script nonce="${nonce}">${script}</script></body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`}});
}
